AUDIO_FILE = "audio_file"
AUDIO_FILES = "audio_files"

START_SECONDS = "start_seconds"
END_SECONDS = "end_seconds"
LABEL = "label"
LABELS = "labels"

PROBABILITIES = "probabilities"
PROBABILITY = "probability"
PER_CLASS = "per_class"
PREDICTIONS = "predictions"
N_PREDICTIONS = "n_predictions"
OVERALL = "overall"

ACCURACY = "accuracy"
ECE = "ece"
MACRO_F1 = "macro_f1"
MICRO_F1 = "micro_f1"
F1 = "f1"
SUPPORT = "support"
PRECISION = "precision"
RECALL = "recall"
PR_AUC = "pr_auc"
LOSS = "loss"

BATCH_SIZE = "batch_size"
LEARNING_RATE = "learning_rate"
EPOCH = "epoch"
EPOCHS = "epochs"
VALIDATION = "validation"
TEST = "test"
TRAIN = "train"
SPLIT = "split"
FOLD = "fold"

SR = "sr"
SAMPLING_RATE = "sampling_rate"
N_MELS = "n_mels"
FIXED_SECONDS = "fixed_seconds"
WINDOW_SECONDS = "window_seconds"

ERROR = "error"

SUMMARY = "summary"
METRICS = "metrics"
PLOTS = "plots"

CORRECTED_LABEL = "corrected_label"
TRUE_LABEL = "true_label"
PRED_LABEL = "pred_label"

LOW_CONFIDENCE = "low_confidence"

MODEL = "model"

REPORT_PATH = "report_path"
CSV_PATH = "csv_path"

METADATA = "metadata"
DATA_DIR = "data_dir"
CREATED_AT = "created_at"
ANNOTATOR = "annotator"
ANNOTATOR_ID = "annotator_id"
N_ITEMS = "n_items"
N_SEGMENTS_WRITTEN = "n_segments_written"
N_SEGEMENTS = "n_segments"
MISSING_AUDIO_FILES = "missing_audio_files"

ARTIFACT = "artifact"
ARTIFACTS = "artifacts"
CHECKSUMS = "checksums"
DATASET = "dataset"
ENV = "env"
GIT = "git"
MANIFEST = "manifest"
HASH = "hash"
SHA = "sha"
SHA256 = "sha256"
SIZE = "size"
PATH = "path"
LOCAL = "local"
COUNTS = "counts"
HOST = "host"
PLATFORM = "platform"
TRACKER = "tracker"
PARAMETERS = "params"

ACTION = "action"
COMMENT = "comment"
TIMESTAMP = "timestamp"

REQUEST_ID = "request_id"
LATENCY = "latency"
N_FILES = "n_files"

# Labels
BURST = "b"
HARMONIC = "h"
MULTIPLE_BURST = "mb"
